name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add mask 1
        run: |
          echo "::add-mask::${{ secrets.CAPTAIN_URL }}"
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
          buildArgs: |
            PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}
      - name: Deploy on VPS
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://${{ secrets.ROOT_DOMAIN }}
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/tsugumik/blazejdrozd.pl:latest'