name: deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Add mask
              run: |
                echo "::add-mask::${{ secrets.CAPTAIN_URL }}"
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Deploy on VPS
              uses: caprover/deploy-from-github@v1.1.2
              with:
                server: https://${{ secrets.ROOT_DOMAIN }}
                app: '${{ secrets.APP_NAME }}'
                token: '${{ secrets.APP_TOKEN }}'
                branch: 'main'